apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadgsch3371-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadgsch3371-tenant-component
    app.kubernetes.io/part-of: loadgsch3371-tenant-app
  name: loadgsch3371-tenant-component
  namespace: loadgsch3371-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadgsch3371-tenant-component
    weight: null
status: {}
